### ISSUE TITLE
Linked List feedback

### ISSUE THREAD

**Issue by lvreynoso** [alexbarksdale/CS-1.2-Intro-Data-Structures#2]
Hi Alex! I've graded your linked list submission for CS 1.2. Here's some feedback:

- good job passing all unit tests
- good job annotating time complexity
- your `delete()` method ends up looping over your nodes twice - there's a way to do it only once, see if you can implement it by also keeping track for the previous node while iterating through the list

**Comment by alexbarksdale** [comment]
Updated the function to keep track of the previous node, thank you!
